# Generated by Django 2.0.5 on 2018-05-04 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_auto_20170820_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='local_dest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='compra_local_estoque', to='estoque.LocalEstoque'),
        ),
    ]
